
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jaime - ST10067405
 */
public class Hospital_Inspections extends javax.swing.JFrame {
    
    /*reference(s): 
     * 1 - Java-Programming-9th-Edition by Joyce Ferrell
     */
    
    public Hospital_Inspections() {
        initComponents();
    }
    
    //Variables
    int MAX = 4;
    
    //array
    ArrayList hospitalName = new ArrayList();
    ArrayList hospitalLocation = new ArrayList();
    ArrayList hospitalYears = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HOSPITAL_NAME_FIELD = new javax.swing.JTextField();
        YEARS_INSPECTION_COMBOBOX = new javax.swing.JComboBox<>();
        HOSPITAL_LOCATION_FIELD = new javax.swing.JTextField();
        SAVE_BUTTON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PRINT_BUTTON = new javax.swing.JButton();
        CLEAR_BUTTON = new javax.swing.JButton();
        ClearMemory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        SaveMenuItem = new javax.swing.JMenuItem();
        PrintMenuItem = new javax.swing.JMenuItem();
        ClearMenuItem = new javax.swing.JMenuItem();
        ClearMemoryMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Inspections");
        setResizable(false);

        jLabel1.setText("Hospital Name:");

        jLabel2.setText("Hospital Location:");

        jLabel3.setText("Years since inspection:");

        HOSPITAL_NAME_FIELD.setPreferredSize(new java.awt.Dimension(56, 24));

        YEARS_INSPECTION_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Year(s)", "2 Year(s)", "3 Year(s)", "4 Year(s)", "5 Year(s)" }));

        HOSPITAL_LOCATION_FIELD.setPreferredSize(new java.awt.Dimension(56, 24));

        SAVE_BUTTON.setText("SAVE");
        SAVE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_BUTTONActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PRINT_BUTTON.setText("PRINT");
        PRINT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINT_BUTTONActionPerformed(evt);
            }
        });

        CLEAR_BUTTON.setText("CLEAR");
        CLEAR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_BUTTONActionPerformed(evt);
            }
        });

        ClearMemory.setText("Clear Memory");
        ClearMemory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMemoryActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        SaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(SaveMenuItem);

        PrintMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        PrintMenuItem.setText("Print");
        PrintMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(PrintMenuItem);

        ClearMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        ClearMenuItem.setText("Clear");
        ClearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ClearMenuItem);

        ClearMemoryMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        ClearMemoryMenuItem.setText("Clear Memory");
        ClearMemoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMemoryMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(ClearMemoryMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PRINT_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CLEAR_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(ClearMemory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SAVE_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HOSPITAL_LOCATION_FIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HOSPITAL_NAME_FIELD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(YEARS_INSPECTION_COMBOBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(HOSPITAL_NAME_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HOSPITAL_LOCATION_FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(YEARS_INSPECTION_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE_BUTTON)
                    .addComponent(ClearMemory))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRINT_BUTTON)
                    .addComponent(CLEAR_BUTTON))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SAVE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVE_BUTTONActionPerformed
        //SAVE BUTTON

        //message to show when maximum is reached
        if (hospitalName.size() == MAX) {
            //JOP to display
            JOptionPane.showMessageDialog(null, "Maximum inspection count reached!");
            
        } else {

            //Adding TextField Information to the ArrayList array
            hospitalName.add(HOSPITAL_NAME_FIELD.getText());
            hospitalLocation.add(HOSPITAL_LOCATION_FIELD.getText());
            hospitalYears.add(YEARS_INSPECTION_COMBOBOX.getSelectedItem());
            
        }
    }//GEN-LAST:event_SAVE_BUTTONActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //MENU ITEM EXIT
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void PRINT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINT_BUTTONActionPerformed
        //PRINT BUTTON
        
        //display variable
        String display = "";
        
        //for-loop to concatenate hospital info for the text area.
        for (int i = 0; i < hospitalName.size(); i++) {
            display += "Hospital Name: " + hospitalName.get(i)
                     + "\nHospital Location: " + hospitalLocation.get(i)
                     + "\nYears since inspection: " + hospitalYears.get(i)
                     + "\n*************************************\n";
        }
        
        //displaying to text area
        jTextArea1.setText(display);
    }//GEN-LAST:event_PRINT_BUTTONActionPerformed

    private void CLEAR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_BUTTONActionPerformed
        //CLEAR BUTTON
        
        //setting text fields to blank
        HOSPITAL_NAME_FIELD.setText("");
        HOSPITAL_LOCATION_FIELD.setText("");
        YEARS_INSPECTION_COMBOBOX.setSelectedIndex(0);
        
        //clearing textarea
        jTextArea1.setText("");
    }//GEN-LAST:event_CLEAR_BUTTONActionPerformed

    private void SaveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuItemActionPerformed
        //MENU ITEM SAVE
        //invoking save method
        SAVE_BUTTONActionPerformed(evt);
    }//GEN-LAST:event_SaveMenuItemActionPerformed

    private void PrintMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintMenuItemActionPerformed
        //MENU ITEM PRINT
        //invoking print method
        PRINT_BUTTONActionPerformed(evt);
    }//GEN-LAST:event_PrintMenuItemActionPerformed

    private void ClearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMenuItemActionPerformed
        //MENU ITEM CLEAR
        //invoking clear method
        CLEAR_BUTTONActionPerformed(evt);
    }//GEN-LAST:event_ClearMenuItemActionPerformed

    private void ClearMemoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMemoryActionPerformed
        //CLEAR MEMORY BUTTON
        
        //removing array elements
        hospitalName.clear();
        hospitalLocation.clear();
        hospitalYears.clear();
        
        //clearing text area
        jTextArea1.setText("");
    }//GEN-LAST:event_ClearMemoryActionPerformed

    private void ClearMemoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMemoryMenuItemActionPerformed
        //MENU ITEM CLEAR MEMORY
        //invoking clear memory method
        ClearMemoryActionPerformed(evt);
    }//GEN-LAST:event_ClearMemoryMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital_Inspections.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital_Inspections().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR_BUTTON;
    private javax.swing.JButton ClearMemory;
    private javax.swing.JMenuItem ClearMemoryMenuItem;
    private javax.swing.JMenuItem ClearMenuItem;
    private javax.swing.JTextField HOSPITAL_LOCATION_FIELD;
    private javax.swing.JTextField HOSPITAL_NAME_FIELD;
    private javax.swing.JButton PRINT_BUTTON;
    private javax.swing.JMenuItem PrintMenuItem;
    private javax.swing.JButton SAVE_BUTTON;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JComboBox<String> YEARS_INSPECTION_COMBOBOX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
